version: '3.8'
services:
  php:
    restart: always
    build: 
      context: ./
      dockerfile: Dockerfile
    ports: 
      - "8001:8080"
  mysql:
    build: ./.docker/mysql
    environment:
      MYSQL_ROOT_PASSWORD: kaito
      MYSQL_DATABASE: shop
    # volumes:
      # - ./.docker/mysql/my.cnf:/etc/mysql/conf.d/my.cnf:ro
      # - ./.docker/mysql/shop.sql:/etc/shop.sql:ro
      # - mysqldata:/var/lib/mysql